- name: Setup Jenkins and Docker on Ubuntu 22.04 LTS
  hosts: jenkins

  tasks:

    - name: Ensure bin directory exists
      ansible.builtin.file:
        path: /home/ubuntu/bin
        state: directory
        mode: '0755'
        owner: ubuntu
        group: ubuntu
      tags: install_kubectl

    - name: Download kubectl binary
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/v1.27.4/bin/linux/amd64/kubectl"
        dest: /home/ubuntu/bin/kubectl
        mode: '0755'
      tags: install_kubectl

    - name: Verify kubectl version
      ansible.builtin.command: /home/ubuntu/bin/kubectl version --client --short
      register: kubectl_version
      changed_when: false
      tags: install_kubectl

    - name: Show kubectl version
      ansible.builtin.debug:
        msg: "kubectl version: {{ kubectl_version.stdout }}"
      tags: install_kubectl

    - name: Copy kubectl to /usr/local/bin
      ansible.builtin.copy:
        src: /home/ubuntu/bin/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
      tags: install_kubectl
