- name: Setup Jenkins, Docker, and SQL Server on Ubuntu 22.04 LTS
  hosts: jenkins
  become: yes

  tasks:
    - name: Remove old Jenkins repo sources and keys if present
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/jenkins.list
        - /etc/apt/trusted.gpg.d/jenkins.gpg
        - /tmp/jenkins.key

    # - name: Update Ubuntu base packages (no Jenkins repo yet)
    #   ansible.builtin.apt:
    #     update_cache: yes

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Enable and start Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started

    - name: Add ubuntu user to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Install Java 17 (recommended for Jenkins)
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: present

    - name: Download Jenkins repo GPG key
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        dest: /tmp/jenkins.key
        mode: '0644'

    - name: Convert Jenkins key to binary and place in trusted.gpg.d
      ansible.builtin.shell: "gpg --dearmor < /tmp/jenkins.key > /etc/apt/trusted.gpg.d/jenkins.gpg"
      args:
        creates: /etc/apt/trusted.gpg.d/jenkins.gpg

    - name: Add Jenkins apt repository
      ansible.builtin.apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
        filename: 'jenkins'
        state: present

    - name: Update apt cache after adding Jenkins repo
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present

    - name: Enable and start Jenkins service
      ansible.builtin.systemd:
        name: jenkins
        enabled: true
        state: started

    # ----- Firewall (ufw, Ubuntu default) -----
    - name: Ensure ufw is installed
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: Allow Jenkins port 8080
      community.general.ufw:
        rule: allow
        port: '8080'
        proto: tcp

    - name: Allow Docker port 2375 (optional)
      community.general.ufw:
        rule: allow
        port: '2375'
        proto: tcp

    - name: Allow SQL Server port 1433
      community.general.ufw:
        rule: allow
        port: '1433'
        proto: tcp

    - name: Ensure ufw is enabled
      community.general.ufw:
        state: enabled

    - name: Print Jenkins initial admin password location
      ansible.builtin.shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
      ignore_errors: yes

    - name: Show Jenkins initial admin password
      ansible.builtin.debug:
        msg: "Jenkins initial password is {{ jenkins_password.stdout | default('Use SSH to retrieve manually if not shown.') }}"
    
    - name: Install AWS CLI v2
      ansible.builtin.apt:
        name: awscli
        state: present

    - name: Install git
      ansible.builtin.apt:
        name: git
        state: present     

    - name: Check git version
      ansible.builtin.shell: git --version
      register: git_version      

    - name: Print git version
      ansible.builtin.debug:
        msg: "{{ git_version.stdout }}"      

    # ----- SQL Server and Tools Setup (Ubuntu) -----
    - name: Import Microsoft GPG key for SQL Server
      ansible.builtin.apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add Microsoft SQL Server repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/22.04/mssql-server-2022 jammy main"
        state: present

    - name: Add Microsoft SQL Tools repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/22.04/prod jammy main"
        state: present

    - name: Install required dependencies for SQL Server and tools
      ansible.builtin.apt:
        name:
          - unixodbc
          - unixodbc-dev
        state: present

    - name: Install SQL Server 2022
      ansible.builtin.apt:
        name: mssql-server
        state: present

    - name: Install mssql-tools and msodbcsql17
      ansible.builtin.apt:
        name:
          - mssql-tools
          - msodbcsql17
        state: present

    - name: Configure SQL Server for unattended install
      ansible.builtin.shell: |
        MSSQL_PID=Express MSSQL_SA_PASSWORD='Cover@2025' /opt/mssql/bin/mssql-conf setup accept-eula
      args:
        creates: /var/opt/mssql/mssql.conf

    - name: Enable and start SQL Server
      ansible.builtin.systemd:
        name: mssql-server
        enabled: true
        state: started

    - name: Add mssql-tools to PATH for all users
      ansible.builtin.lineinfile:
        path: /etc/profile.d/mssql-tools.sh
        line: 'export PATH="$PATH:/opt/mssql-tools/bin"'
        create: yes
        mode: '0755'
    # ----- SQL Server and Tools Setup END -----
